---
title: "R Notebook"
output: html_notebook
---


```{r}
read_exp1 = read.csv('experiment_01_simon_laptop.csv')
read_exp2 = read.csv('experiment_02_simon_laptop.csv')
```

```{r}
library(datasets) #Load the datasets package
#attach(iris) #Attach iris data to the R search path
library(dplyr)
library(ggplot2)
```

```{r}
exp1_averageTotal = read_exp1 %>%
  group_by(ThreadCount, Algorithm) %>%
  summarise(avgTimeTotal = mean(TimeTotal))

exp1_minimumTime = exp1_averageTotal %>%
  slice_min(avgTimeTotal)
  
exp1_averageSort = read_exp1 %>%
  group_by(ThreadCount, Algorithm) %>%
  summarise(avgTimeSort = mean(TimeSort))

```
```{r}
ggplot(exp1_averageTotal, aes(x=ThreadCount, y=avgTimeTotal, fill=Algorithm))+
  geom_bar(stat='identity', position='dodge')

ggplot(exp1_averageSort, aes(x=ThreadCount, y=avgTimeSort, fill=Algorithm))+
  geom_bar(stat='identity', position='dodge')
```

```{r}
exp2 = read_exp2 %>%
  filter(
    (Algorithm == "merge" & ThreadCount == 15) |
    (Algorithm == "quick" & ThreadCount == 5) |
    !(Type %in% c("mta"))
  )
```


```{r}
exp2_i3 = exp2 %>% filter(InputSize == 1e+3)
exp2_i4 = exp2 %>% filter(InputSize == 1e+4)
exp2_i5 = exp2 %>% filter(InputSize == 1e+5)
exp2_i6 = exp2 %>% filter(InputSize == 1e+6)
exp2_i7 = exp2 %>% filter(InputSize == 1e+7)
exp2_i8 = exp2 %>% filter(InputSize == 1e+8)
exp2_i9 = exp2 %>% filter(InputSize == 1e+9)


```

```{r}
pi3 <- ggplot(exp2_i3, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi3
```
```{r}
pi4 <- ggplot(exp2_i4, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi4
```
```{r}
pi5 <- ggplot(exp2_i5, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi5
```
```{r}
pi6 <- ggplot(exp2_i6, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi6
```
```{r}
pi7 <- ggplot(exp2_i7, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi7
```
```{r}
pi8 <- ggplot(exp2_i8, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi8
```
```{r}
pi9 <- ggplot(exp2_i9, aes(x=Type, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
pi9
```




```{r}
exp2_merge_sta = exp2 %>%
  filter(
    (Algorithm == "merge" & Type == "sta")
  )

exp2_merge_mta = exp2 %>%
  filter(
    (Algorithm == "merge" & Type == "mta")
  )

exp2_quicke_sta = exp2 %>%
  filter(
    (Algorithm == "quick" & Type == "sta")
  )

exp2_quick_mta = exp2 %>%
  filter(
    (Algorithm == "quick" & Type == "mta")
  )

```

```{r}
p <- ggplot(exp2_merge_sta, aes(x=InputSize, y=TimeTotal))+
  geom_bar(stat="identity", color="blue", fill="white")

p + coord_flip()
```


```{r}
p <- ggplot(exp2_merge_mta, aes(x=InputSize, y=TimeTotal))+
  geom_bar(stat="identity", color="blue", fill="white")

p + coord_flip()
```

```{r}
p <- ggplot(exp2_quicke_sta, aes(x=InputSize, y=TimeTotal))+
  geom_bar(stat="identity", color="blue", fill="white")

p + coord_flip()
```

```{r}
p <- ggplot(exp2_quick_mta, aes(x=InputSize, y=TimeTotal))+
  geom_bar(stat="identity", color="blue", fill="white")

p + coord_flip()
```

```{r}
exp2_below_e5 = exp2%>%
  filter(
    (InputSize < 1e+5)
  )
  

exp2_e6 = exp2 %>%
  filter(
    (InputSize >= 1e+5)
  )

```

```{r}
p <- ggplot(exp2_below_e5, aes(x=InputSize, y=TimeSort, fill = Algorithm))+
  geom_bar(stat='identity', position='dodge')
p
```
